---
- hosts: localhost
  connection: local
  gather_facts: false
#  vars_files:
#  - vars/common.yml
#  - vars/k8s.yml
  tasks:
  - name: Create resource group
    include_tasks: create_resource_group.yml

  - name: Create (or update) SQL Database
    azure.azcollection.azure_rm_sqldatabase:
      resource_group: abs-az-resource-group
      server_name: abs-az-sql-db-server
      name: abs-az-sql-db
      location: eastus
