---
- hosts: localhost
  connection: local
  gather_facts: false
#  vars_files:
#  - vars/common.yml
#  - vars/k8s.yml
  tasks:
  - name: Create resource group
    include_tasks: tasks/create_resource_group.yml

  - name: Create a storage account
    azure.azcollection.azure_rm_storageaccount:
      resource_group: abs-az-resource-group
      name: absazstorageacct
      type: Standard_RAGRS
      tags:
        testing: testing
        delete: on-exit