---
- hosts: localhost
  connection: local
  gather_facts: false
#  vars_files:
#  - vars/common.yml
#  - vars/k8s.yml
  tasks:
  - name: Create resource group
    include_tasks: create_resource_group.yml

  - name: Create a Virtual Network (VNET)
    include_tasks: create_virtual_network.yml

  - name: Create gateway subnet
    include_tasks: create_subnet.yml
    vars:
      subnet_name: abs_az_app_gateway_subnet
      resource_gp: abs-az-resource-group
      addr_prefix: 10.0.1.0/24
      vnet: abs-az-vnet

  - name: Get gateway subnet facts
    azure_rm_subnet_info:
      resource_group: abs-az-resource-group
      virtual_network_name: abs-az-vnet
      name: abs_az_app_gateway_subnet
    register: gateway_subnet
  - debug:
      var: gateway_subnet.subnets[0].id

  - name: Create frontend subnet
    include_tasks: create_subnet.yml
    vars:
      subnet_name: abs_az_ag_frontend_subnet
      resource_gp: abs-az-resource-group
      addr_prefix: 10.0.2.0/24
      vnet: abs-az-vnet

  - name: Get frontend subnet facts
    azure_rm_subnet_info:
      resource_group: abs-az-resource-group
      virtual_network_name: abs-az-vnet
      name: abs_az_ag_frontend_subnet
    register: frontend_subnet
  - debug:
      var: frontend_subnet.subnets[0].id

  - name: Create a frontend public IP address
    include_tasks: create_public_ip.yml
    vars:
      name: abs-az-frontend-public-ip
      resource_group: abs-az-resource-group
      allocation_method: Static

  # # - name: Create a Network Security Group (NSG)
  # #   include_tasks: create_network_security_group.yml

  # # - name: Create a virtual Network Interface Card (NIC)
  # #   include_tasks: create_network_interface_card.yml

  # # - name: Create a storage account
  # #   include_tasks: create_storage_account.yml

  # - name: Create instance of Application Gateway
  #   azure.azcollection.azure_rm_appgateway:
  #     resource_group:  abs-az-resource-group
  #     name:  abs-az-app-gateway
  #     sku:
  #       name: standard_small
  #       tier: standard
  #       capacity: 2
  #     gateway_ip_configurations:
  #       - subnet:
  #           id: gateway_subnet.subnets[0].id.value
  #         name: abs_az_app_gateway_ip_config
  #     frontend_ip_configurations:
  #       - subnet:
  #           id: frontend_subnet.subnets[0].id.value
  #         name: abs_az_gateway_frontend_ip_config
  #     frontend_ports:
  #       - port: 90
  #         name: abs_az_app_gateway_frontend_port
  #     backend_address_pools:
  #       - backend_addresses:
  #           - ip_address: 10.0.0.4
  #         name: abs_az_backend_address_pool
  #     backend_http_settings_collection:
  #       - port: 80
  #         protocol: http
  #         cookie_based_affinity: enabled
  #         name: abs_az_app_gateway_http_settings
  #     http_listeners:
  #       - frontend_ip_configuration: abs_az_gateway_frontend_ip_config
  #         frontend_port: abs_az_app_gateway_frontend_port
  #         name: abs_az_http_listener
  #     request_routing_rules:
  #       - rule_type: Basic
  #         backend_address_pool: abs_az_backend_address_pool
  #         backend_http_settings: abs_az_app_gateway_http_settings
  #         http_listener: abs_az_http_listener
  #         name: rule1