- name: Create a public IP address
  azure.azcollection.azure_rm_publicipaddress:
    name: "{{ public_ip_name }}"
    resource_group: "{{ resource_group }}"
    allocation_method: Static
  register: output_ip_address

- name: Print Public IP of VM
  debug:
    msg: "The public IP of VM is {{ output_ip_address.state.ip_address }}."